# TODO: i18 Support


fonts_api:
  google: https://fonts.googleapis.com/css?family=
  active: google

menu:
  getting-started:
    label: 开始使用
    href: /getting-started.html
  theme-settings:
    label: 主题配置
    href: /theme-settings.html
#    subItems:
#      theme-settings-example:
#        label: 主题配置示例
#        href: /theme-settings-example.html
  third-party-services:
    label: 第三方服务
    href: /third-party-services.html
  tag-plugins:
    label: 内建标签
    href: /tag-plugins.html
  advanced-settings:
    label: 进阶设定
    href: /advanced-settings.html
  faqs:
    label: 常见问题
    href: /faqs.html
